#!/usr/bin/env bash

OS="$(uname)"
USERNAME="$USER"
HOMEBREW_BIN="/opt/homebrew/bin/brew" # defaults to macOS...

echo -e "\n🚀 Executing remote-bootstrap... dotfiles.git → ~/.dotfiles\n" && sleep 2

#######################################################################
### check for supported system
if [[ "$OS" != "Linux" && "$OS" != "Darwin" ]]; then
  echo "💣 Didn't find a supported system! ($OS not in [Linux, Darwin])" && exit 1
elif [[ "$OS" == "Linux" ]]; then
  [ -f /etc/os-release ] && . /etc/os-release && OS=$ID
  if [[ "$OS" != "debian" ]]; then
    echo "💣 Didn't find a supported Linux! ($OS is not in [debian])" && exit 1
  fi
fi

if [[ "$OS" == "debian" ]]; then
  #######################################################################
  ### Linux: ensure mandatory tools
  INSTALLED_ANY_MANDATORY_TOOL=0

  # (do this 1st to have zsh as the default shell after relog 😎)
  type zsh &> /dev/null
  if [[ $? -ne 0 ]]; then
    echo "🚧 Installing 'zsh' and making it the default shell!" && sleep 2
    su root -c "export PATH=/usr/sbin:$PATH;apt -y install zsh;chsh -s /bin/zsh $USERNAME;exit 0"
    INSTALLED_ANY_MANDATORY_TOOL=1
  fi
  type curl &> /dev/null
  if [[ $? -ne 0 ]]; then
    echo "🚧 Installing 'curl'!" && sleep 2
    su root -c "export PATH=/usr/sbin:$PATH;apt -y install curl;exit 0"
    INSTALLED_ANY_MANDATORY_TOOL=1
  fi

  type sudo &> /dev/null
  if [[ $? -ne 0 ]]; then
    echo "🚧 Installing missing 'sudo'!" && sleep 2
    su root -c "export PATH=/usr/sbin:$PATH;apt -y install sudo;usermod -aG sudo $USERNAME;exit 0"
    INSTALLED_ANY_MANDATORY_TOOL=1
  fi

  if [[ $INSTALLED_ANY_MANDATORY_TOOL -ne 0 ]]; then
    echo "💣 Please relog the shell to finish madantory tools setup! Then rerun this script again!" && exit 0
  fi
fi

# and Nix itself
echo "🚧 Installing 'Nix'!" && sleep 2
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

# make Nix directly usable!
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

# install the first mandatory Nix packages before proceeding
echo "🚧 Installing 'git' and 'chezmoi' via Nix!" && sleep 2
nix profile install nixpkgs#{git,chezmoi}

#######################################################################
### apply dotfiles using chezmoi
echo "This would have invoked chezmoi!"
#chezmoi init -S ~/.dotfiles --branch linux-nix --apply n4tht4n

echo "👍 We're done, please relog and enjoy your freshly installed system 😎 🚀"

